spring:
  application:
    name: spring-boot-test-vault
  profiles:
    active: dev

  cloud:
    vault:
      host: localhost
      port: 8200
      token: root
      scheme: http
      kv:
        backend: spring-microservices
        default-context: shared-config
        application-name: ${spring.application.name}

  config:
    import: optional:vault://

external-api:
  uri: https://external-api-for-spring-boot-test-vault.com/v1/